name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # 如果使用了主题submodule
          fetch-depth: 0    # 获取所有历史提交，确保主题submodule更新

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # 或指定版本 '0.121.1'
          extended: true         # 如果主题需要 extended 版本

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hugo 默认输出目录
          # publish_branch: gh-pages # 默认是 gh-pages 分支
